remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme

title: [Julia Romanovska]
description: [Hello! I have always been interested in the process of creating websites, and finally, thanks to mentor support, I have my first projects (and mini-projects :) )
The most exciting thing for me is the moment of turning complex into simple.]
