theme: jekyll-theme-architect
title: [Lazy Loading]

remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme 

title: [Romanovska Julia]
description: [A short description of your site's purpose]
